"use client";

import { useMemo, useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { CircleDollarSign, Plus, ReceiptText } from "lucide-react";
import { getSupabaseBrowserClient } from "@/lib/supabase/browser";
import type { BarberAppointment, BarberAppContext, BarberCashReceipt, BarberCashSession, BarberCustomer, BarberFinancialAccount } from "./types";
import styles from "./barber.module.css";

const money = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });
const paymentMethods = ["CASH", "PIX", "CARD", "BOLETO", "TRANSFER", "OTHER"];
function cents(value: FormDataEntryValue | null) { return Math.round(Number(String(value ?? "").replace(/[R$\s.]/g, "").replace(",", ".")) * 100); }

export function BarberCash({ context, sessions, receipts, accounts, appointments, customers, outstandingByAppointment }: { context: BarberAppContext; sessions: BarberCashSession[]; receipts: BarberCashReceipt[]; accounts: BarberFinancialAccount[]; appointments: BarberAppointment[]; customers: BarberCustomer[]; outstandingByAppointment: Map<string, number> }) {
  const router = useRouter(); const [open, setOpen] = useState(false); const [message, setMessage] = useState("");
  const customerById = useMemo(() => new Map(customers.map((item) => [item.id, item.full_name])), [customers]);
  const receivable = appointments.filter((item) => (outstandingByAppointment.get(item.id) ?? 0) > 0);
  const current = sessions.find((item) => item.status === "OPEN");
  async function adjust(receipt: BarberCashReceipt) { const amount = window.prompt("Novo valor recebido (R$):", (receipt.amount_cents / 100).toFixed(2).replace(".", ",")); if (!amount) return; const reason = window.prompt("Motivo da correção:"); if (!reason?.trim()) return; const value = cents(amount); if (!value) { setMessage("Informe um valor válido."); return; } const supabase = getSupabaseBrowserClient(); const { error } = await supabase!.rpc("adjust_barber_cash_receipt", { p_receipt_id: receipt.id, p_new_amount_cents: value, p_reason: reason.trim(), p_idempotency_key: `barber:receipt-adjust:${crypto.randomUUID()}` }); if (error) { setMessage(error.message); return; } setMessage("Correção registrada no histórico do Caixa."); router.refresh(); }
  async function receive(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); const amount = cents(data.get("amount")); if (!amount) { setMessage("Informe um valor válido."); return; } const supabase = getSupabaseBrowserClient(); const { error } = await supabase!.rpc("record_barber_appointment_receipt", { p_appointment_id: String(data.get("appointment_id")), p_amount_cents: amount, p_payment_method: String(data.get("payment_method")), p_financial_account_id: String(data.get("financial_account_id")), p_reference: String(data.get("reference") ?? "").trim() || null, p_idempotency_key: `barber:receipt:${crypto.randomUUID()}` }); if (error) { setMessage(error.message); return; } setMessage("Recebimento registrado no seu Caixa e aguardando conciliação."); setOpen(false); router.refresh(); }
  return <><section className={styles.hero}><div><p className={styles.eyebrow}>{context.organization_name}</p><h1 className={styles.title}>Meu Caixa</h1><p className={styles.muted}>Você vê apenas seus recebimentos. O Gestor concilia e confirma os valores ao final do dia.</p></div><button className={styles.button} onClick={() => setOpen(true)}><Plus size={16} /> Receber atendimento</button></section>
    {message && <p className={styles.notice} role="status">{message}</p>}
    <section className={styles.grid}><article className={styles.card}><h2>Caixa de hoje</h2><p className={styles.amount}>{current ? money.format(current.expected_cents / 100) : money.format(0)}</p><span className={styles.muted}>{current ? "Aberto para recebimentos" : "Abre no primeiro atendimento"}</span></article><article className={styles.card}><h2>Sessões recentes</h2><div className={styles.list}>{sessions.length ? sessions.slice(0, 4).map((session) => <div className={styles.row} key={session.id}><span>{new Intl.DateTimeFormat("pt-BR").format(new Date(`${session.business_date}T12:00:00`))}</span><strong>{money.format(session.expected_cents / 100)}</strong><span className={styles.status}>{session.status === "OPEN" ? "ABERTO" : "CONCILIADO"}</span></div>) : <span className={styles.muted}>Nenhuma sessão aberta.</span>}</div></article></section>
    <section className={styles.card}><h2><ReceiptText size={18} /> Meus recebimentos</h2><div className={styles.list}>{receipts.length ? receipts.map((receipt) => <div className={styles.row} key={receipt.id}><div><strong>{receipt.customer_name}</strong><span className={styles.muted}>{receipt.payment_method} · {receipt.financial_account_name}</span></div><div><strong>{money.format(receipt.amount_cents / 100)}</strong><span className={receipt.status === "RECONCILED" ? styles.success : receipt.status === "REVERSED" ? styles.danger : styles.muted}>{receipt.status === "RECONCILED" ? "Conciliado" : receipt.status === "REVERSED" ? "Corrigido" : "Aguardando conciliação"}</span>{receipt.status === "PENDING_RECONCILIATION" && <button className={`${styles.button} ${styles.secondary}`} onClick={() => void adjust(receipt)}>Corrigir</button>}</div></div>) : <p className={styles.muted}>Nenhum recebimento registrado.</p>}</div></section>
    {open && <div className={styles.modal}><form className={styles.dialog + " " + styles.form} onSubmit={receive}><h2><CircleDollarSign size={19} /> Receber atendimento</h2><p className={styles.muted}>O valor não altera o preço do atendimento. Correções antes da conciliação preservam histórico.</p><label>Atendimento<select name="appointment_id" required><option value="">Selecione</option>{receivable.map((item) => <option key={item.id} value={item.id}>{customerById.get(item.customer_id) ?? "Cliente"} · saldo {money.format((outstandingByAppointment.get(item.id) ?? 0) / 100)}</option>)}</select></label><label>Valor recebido (R$)<input name="amount" inputMode="decimal" placeholder="0,00" required /></label><label>Forma de recebimento<select name="payment_method">{paymentMethods.map((item) => <option key={item} value={item}>{item === "CASH" ? "Dinheiro" : item === "CARD" ? "Cartão" : item}</option>)}</select></label><label>Conta de destino<select name="financial_account_id" required><option value="">Selecione</option>{accounts.map((account) => <option key={account.id} value={account.id}>{account.name} · {account.kind === "CASH" ? "Caixa" : "Banco"}</option>)}</select></label><label>Observação<input name="reference" maxLength={240} /></label><div className={styles.formActions}><button type="button" className={`${styles.button} ${styles.secondary}`} onClick={() => setOpen(false)}>Cancelar</button><button className={styles.button}>Confirmar recebimento</button></div></form></div>}</>;
}
