"use client";

import { useRef, useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import Image from "next/image";
import { Camera } from "lucide-react";
import { normalizePhoneE164 } from "@/lib/phone";
import { getSupabaseBrowserClient } from "@/lib/supabase/browser";
import type { BarberAppContext } from "./types";
import styles from "./barber.module.css";

export function BarberProfile({ context }: { context: BarberAppContext }) {
  const router = useRouter(); const input = useRef<HTMLInputElement>(null); const [message, setMessage] = useState(""); const [avatarUrl, setAvatarUrl] = useState(context.barber_avatar_url);
  async function uploadPhoto(file: File) { if (!/^image\/(png|jpeg|webp)$/u.test(file.type) || file.size > 2 * 1024 * 1024) throw new Error("Use PNG, JPEG ou WebP de até 2 MB."); const supabase = getSupabaseBrowserClient(); if (!supabase) throw new Error("Supabase indisponível."); const path = `${context.organization_id}/${context.barber_id}/${crypto.randomUUID()}.webp`; const { error } = await supabase.storage.from("barber-avatars").upload(path, file, { contentType: file.type, cacheControl: "31536000" }); if (error) throw error; return supabase.storage.from("barber-avatars").getPublicUrl(path).data.publicUrl; }
  async function save(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); try { const file = data.get("avatar"); const newAvatar = file instanceof File && file.size ? await uploadPhoto(file) : avatarUrl; const whatsapp = normalizePhoneE164(String(data.get("whatsapp") ?? "").trim()); if (String(data.get("whatsapp") ?? "").trim() && !whatsapp) throw new Error("Informe um WhatsApp válido."); const supabase = getSupabaseBrowserClient(); const { error } = await supabase!.rpc("update_my_barber_profile", { p_organization_id: context.organization_id, p_display_name: String(data.get("display_name") ?? "").trim(), p_whatsapp_e164: whatsapp, p_bio: String(data.get("bio") ?? "").trim() || null, p_avatar_url: newAvatar }); if (error) throw error; setAvatarUrl(newAvatar); setMessage("Perfil atualizado."); router.refresh(); } catch (error) { setMessage(error instanceof Error ? error.message : "Não foi possível atualizar o perfil."); } }
  return <><section className={styles.hero}><div><p className={styles.eyebrow}>{context.organization_name}</p><h1 className={styles.title}>Meu Perfil</h1><p className={styles.muted}>Edite somente seus dados de contato e apresentação.</p></div></section>{message && <p className={styles.notice} role="status">{message}</p>}<form className={styles.card + " " + styles.form} onSubmit={save}><div className={styles.row}>{avatarUrl ? <Image src={avatarUrl} alt="Foto de perfil" width={78} height={78} style={{ borderRadius: "50%", objectFit: "cover" }} /> : <span className={styles.status}>Sem foto</span>}<button type="button" className={`${styles.button} ${styles.secondary}`} onClick={() => input.current?.click()}><Camera size={16} /> Trocar foto</button><input ref={input} name="avatar" type="file" accept="image/png,image/jpeg,image/webp" hidden /></div><label>Nome<input name="display_name" defaultValue={context.barber_name} minLength={2} required /></label><label>WhatsApp<input name="whatsapp" defaultValue={context.barber_whatsapp_e164 ?? ""} inputMode="tel" /></label><label>Descrição de perfil<textarea name="bio" defaultValue={context.barber_bio ?? ""} maxLength={1000} /></label><div className={styles.formActions}><button className={styles.button}>Salvar alterações</button></div></form></>;
}
